### ISSUE TITLE
License / Authors

### ISSUE THREAD

**Issue by jonasstein** [OpenA/color-lines-sdl#3]
I guess the license and authors information covers just the c code.
Please review the media files too. Are the sound/gfx files really under GPL?

The reuse tool might be useful to track the licenses properly for all files in the project.
https://reuse.software/

**Comment by OpenA** [comment]
Graphics is now gpl / free.
For music tracks i added authors, because this tracks from modarchive and license is unknown

**Comment by jonasstein** [comment]
How do you know that you may redistribute the music then? It may be better to replace the files with music files under a free licence.
